### ISSUE TITLE
Can't find chessboard

### ISSUE THREAD

**Issue by arn13** [dakotabenjamin/CameraCalibration#10]
Hi, I took 11 images to calibrate my Mavic. I used the 7x9 chessboard that is suggested.
Unfortunately the chessboard can not be found in any of the images. Any Idea why that is?
`DEBUG:Namespace(images='./mavic/chessboard/', out=None, pattern_x=7, pattern_y=9, square_size=1.0)
img:  ['DJI_0001.JPG', 'DJI_0005.JPG', 'DJI_0004.JPG', 'DJI_0009.JPG', 'DJI_0008.JPG', 'DJI_0007.JPG', 'DJI_0011.JPG', 'DJI_0002.JPG', 'DJI_0010.JPG', 'DJI_0006.JPG', 'DJI_0003.JPG']
processing DJI_0001.JPG... chessboard not found
processing DJI_0005.JPG... chessboard not found
processing DJI_0004.JPG... chessboard not found
processing DJI_0009.JPG... chessboard not found
processing DJI_0008.JPG... chessboard not found
processing DJI_0007.JPG... chessboard not found
processing DJI_0011.JPG... chessboard not found
processing DJI_0002.JPG... chessboard not found
processing DJI_0010.JPG... chessboard not found
processing DJI_0006.JPG... chessboard not found
processing DJI_0003.JPG... chessboard not found
OpenCV Error: Assertion failed (nimages > 0) in calibrateCamera, file /build/opencv-SviWsf/opencv-2.4.9.1+dfsg/modules/calib3d/src/calibration.cpp, line 3415
Traceback (most recent call last):
  File "opencv_calibrate.py", line 117, in <module>
    rms, camera_matrix, dist_coefs, rvecs, tvecs = cv2.calibrateCamera(obj_points, img_points, (w, h), None, None)
cv2.error: /build/opencv-SviWsf/opencv-2.4.9.1+dfsg/modules/calib3d/src/calibration.cpp:3415: error: (-215) nimages > 0 in function calibrateCamera
`

Also I would suggest to create a calibration database if a existing calibration can be used for a different camera.

**Comment by dakotabenjamin** [comment]
Can you share a sample chessboard photo?

We are looking into ways to build a database

**Comment by dakotabenjamin** [comment]
Also try 8x10 in the command call

**Comment by arn13** [comment]
Thanks that did it.
