### ISSUE TITLE
ERROR:Failed to write to exif: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by theincorrect** [dakotabenjamin/CameraCalibration#7]
`DEBUG:Undistorting DJI_0126.JPG . . .
DEBUG:['exiftool', '-TagsFromFile', '/home/kg.ru/kornev/field38/images/DJI_0126.JPG', '-all:all', '/home/kg.ru/kornev/field38/images/out/DJI_0126.JPG']
ERROR:Failed to write to exif: [Errno 2] No such file or directory`

Getting this error for every image. They do exist in directory _out_ when script is done.

**Comment by theincorrect** [comment]
As described in installation section:
`sudo apt-get install python-opencv exiftool`

That solved the problem.

**Comment by edderleonardo** [comment]
https://exiftool.org/install.html
