### ISSUE TITLE
Chessboard dimensions parameters are different from actual

### ISSUE THREAD

**Issue by theincorrect** [dakotabenjamin/CameraCalibration#8]
When launching calibration you have to set width of board as (x - 1) and height as (y - 1). It's confusing and not noticed in usage description in readme.

Would be great if you can fix this.

**Comment by dakotabenjamin** [comment]
https://github.com/dakotabenjamin/CameraCalibration/commit/4e63a55944d8f83c8ddb891f755b6855a620988e see this fix
